config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  resources :recipes

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients
  accepts_nested_attributes_for :ingredients, :allow_destroy => true, reject_if: proc { |attributes| attributes['name'].blank? }

  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    @recipe.ingredients.build # build ingredient attributes, nothing new here
  end

  def create
#    debugger
    @recipe = Recipe.new(recipe_params)
    if params[:add_ingredient]
      # add empty ingredient associated with @recipe
      @recipe.ingredients.build
    elsif params[:remove_ingredient]
      # nested model that have _destroy attribute = 1 automatically deleted by rails
    else
      # save goes like usual
      if @recipe.save
        flash[:notice] = "Successfully created recipe."
        redirect_to @recipe and return
      end
    end
    render :action => 'new'
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if params[:add_ingredient]
    	# rebuild the ingredient attributes that doesn't have an id
    	unless params[:recipe][:ingredients_attributes].blank?
	  for attribute in params[:recipe][:ingredients_attributes]
	    @recipe.ingredients.build(attribute.last.except(:_destroy)) unless attribute.last.has_key?(:id)
	  end
    	end
      # add one more empty ingredient attribute
      @recipe.ingredients.build
    elsif params[:remove_ingredient]
      # collect all marked for delete ingredient ids
      removed_ingredients = params[:recipe][:ingredients_attributes].collect { |i, att| att[:id] if (att[:id] && att[:_destroy].to_i == 1) }
      # physically delete the ingredients from database
      Ingredient.delete(removed_ingredients)
      flash[:notice] = "Ingredients removed."
      for attribute in params[:recipe][:ingredients_attributes]
      	# rebuild ingredients attributes that doesn't have an id and its _destroy attribute is not 1
        @recipe.ingredients.build(attribute.last.except(:_destroy)) if (!attribute.last.has_key?(:id) && attribute.last[:_destroy].to_i == 0)
      end
    else
      # save goes like usual
      if @recipe.update_attributes(recipe_params)
        flash[:notice] = "Successfully updated recipe."
        redirect_to @recipe and return
      end
    end
    render :action => 'edit'
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = "Successfully destroyed recipe."
    redirect_to recipes_url
  end
  
  private
    def recipe_params
      params.require(:recipe).permit(:name,:description,ingredients_attributes:[:name,:_destroy,:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecepiesBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<h2>Form</h2>
<%= form_for @recipe do |f| %>
  <%# f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 4, :cols => 50 %>
  </p>
  <h3>Ingredients</h3>
  <ol>
    <%= f.fields_for :ingredients do |ing| %>
      <li>
        <%= ing.label :name %>
        <%= ing.text_field :name, :size => 50 %>
        <%= ing.check_box :_destroy %>
        <%= ing.label :_destroy, 'delete' %>
      </li>
    <% end %>
  </ol>
  <p>
    <%= f.submit 'Add ingredient', :name => "add_ingredient"    %>
    <%= f.submit 'Delete checked', :name => "remove_ingredient" %>
    <%= f.submit %>
    <%= link_to 'back', recipes_path %>
  </p>
<% end %>

app/views/recipes/edit.html.erb
<h1>Recipes#edit</h1>
<%= render 'form' %>

app/views/recipes/index.html.erb
<h1>Recipes#index</h1>
<p>Find me in app/views/recipes/index.html.erb</p>
<ul>
  <% @recipes.each do |recipe|  %>
    <%= link_to recipe.name.capitalize, recipe %>: <%= recipe.description %>
  <% end %>
</ul>
<%= link_to 'Nova', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>Recipes#new</h1>
<%= render 'form' %>

app/views/recipes/show.html.erb
<h1>Recipes#show</h1>
<p>Find me in app/views/recipes/show.html.erb</p>
<h2><%= @recipe.name.capitalize %></h2> <%= link_to 'Edit', edit_recipe_path(@recipe) %>
<p><%= @recipe.description %><p/>
<h3>Ingredients:</h3>
<ol>
  <% @recipe.ingredients.each do |ingredient| %>
    <li><%= ingredient.name %></li>
  <% end %>
</ol>